config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "schedules#index"
  resources :schedules
  resources :users, only: :show
  resources :cars
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_one :schedule

  with_options presence: true do
    validates :car_name
    validates :car_number
    validates :car_model
  end

  validates :car_number, numericality: { only_integer: true, message: 'is invalid. Input only number' }, allow_blank: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  belongs_to :car

  with_options presence: true do
    validates :title
    validates :content
  end

  validate :start_check
  validate :start_end_check
  validate :car_valid_check

  def start_check
    errors.add(:start_time, 'は現在の時間以降を選択してください') if start_time < Time.now
  end

  def start_end_check
    errors.add(:end_time, 'は開始時刻より遅い時間を選択してください') if start_time > end_time
  end

  def car_valid_check
    overlapped_schedules = Schedule
                           .where(car_id: car_id)
                           .where('end_time > ?', start_time)
                           .where('start_time < ?', end_time)
                           .where.not(id: id)                      # 過去に登録したscheduleで引っかからないようにする

    errors.add(:car_id, 'はこの時間に使用できません') if overlapped_schedules.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :schedules

  validates :nickname, presence: true, uniqueness: { case_sensitive: true }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字の両方を含める必要があります' }, allow_blank: true

  with_options allow_blank: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角文字を使用してください' } do
    validates :family_name
    validates :first_name
  end

  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :birthday, presence: true
  validates :occupation, presence: true
  validates :phone_number, presence: true                    # 直す
  validates :phone_number, numericality: { only_integer: true, message: 'is invalid. Input only number' },
                           length: { minimum: 10, maximum: 11 }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:nickname, :family_name, :first_name, :birthday, :occupation, :phone_number])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_car, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to car_path
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to root_path
  end

  private

  def car_params
    params.require(:car).permit(:car_name, :car_number, :car_model).merge(user_id: current_user.id)
  end

  def set_car
    @car = Car.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless @car.user_id == current_user.id
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_schedule, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to schedule_path
    else
      render :edit
    end
  end

  def destroy
    @schedule.destroy
    redirect_to root_path
  end

  private

  def schedule_params
    params.require(:schedule).permit(:title, :start_time, :end_time, :car_id, :content).merge(user_id: current_user.id)
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless @schedule.user_id == current_user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @nickname = current_user.nickname
    @schedules = current_user.schedules.order(start_time: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/edit.html.erb
<div class='form-header'>
  <h1 class='form-header-text'>
    車編集機能
  </h1>
</div>

<%= form_with(model: @car, local: true) do |f| %>

<%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">車名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :car_name, class:"input-default", id:"car-title" %>
  </div>


  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">車のナンバー</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :car_number, class:"input-default", id:"car-title" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">車種</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :car_model, class:"input-default", id:"car-title" %>
  </div>


  <div class="car-edit-submit">
    <%= f.submit "変更する", class:"save-btn"%>
    <%= link_to "戻る", car_path(@car.id), class:"back-btn"%>
  </div>

<% end %>

app/views/cars/index.html.erb
<div class='form-header'>
  <h1 class='form-header-text'>
    車一覧
  </h1>
</div>

  <% @cars.each do |car| %>
    <p class="border-line"> ------------------------------------------------------------------------------- </p>
    
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">車名</label>
      </div>
      <p class="car-index-text">
        <%= link_to car.car_name, car_path(car.id), class:"car-index-link" %>
      </p>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">持ち主</label>
      </div>
      <p class="car-index-text">
        <%= car.user.nickname %>
      </p>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">車のナンバー</label>
      </div>
      <p class="car-index-text">
        <%= car.car_number %>
      </p>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">車種</label>
      </div>
      <p class="car-index-text">
        <%= car.car_model %>
      </p>
    </div>
  <% end %>

  <div class="submit">
    <%= link_to '戻る', root_path, class:'back-btn' %>
  </div>
</div>

app/views/cars/new.html.erb
<div class='form-header'>
  <h1 class='form-header-text'>
    車種追加
  </h1>
</div>


<%= form_with(model: @car, local: true) do |f| %>

<%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">車名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :car_name, class:"input-default", id:"password", placeholder:"" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">車のナンバー</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :car_number, class:"input-default", id:"password", placeholder:"" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">車種</label>
    </div>
    <%= f.text_field :car_model, class:"input-default", id:"password", placeholder:"" %>
  </div>


  <div class="car-new-submit">
    <%= f.submit "保存する", class:"save-btn"%>
    <%= link_to "戻る", root_path, class:"back-btn"%>
  </div>

<% end %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>
<div class='form-header'>
  <h1 class='form-header-text'>
    車詳細ページ
  </h1>
</div>


<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">車名</label>
  </div>
  <p class="schedule-show-text"><%= @car.car_name %></p>
</div>

<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">持ち主</label>
  </div>
  <p class="schedule-show-text"><%= @car.user.nickname %></p>
</div>

<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">車のナンバー</label>
  </div>
  <p class="schedule-show-text"><%= @car.car_number %></p>
</div>

<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">車種</label>
  </div>
  <p class="schedule-show-text"><%= @car.car_model %></p>
</div>

<div class="submit">
<% if user_signed_in? && current_user.id == @car.user_id %>
  <%= button_to "編集", edit_car_path(@car.id), method: :get, class:"edit-btn" %>
  <%= button_to "削除", car_path(@car.id), method: :delete, data: { confirm: 'Are you Sure?' } ,class:'delete-btn' %>
<% end %>
<%= link_to '戻る', root_path ,class:"back-btn"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<div class='form-header'>
  <h1 class='form-header-text'>
    予約内容変更
  </h1>
</div>

<%= form_with(model: @schedule, local: true) do |f| %>

<%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class="user-text-wrap">
      <label class="user-name">ユーザー名</label>
    </div>
    <div class="car-name">
      <%= @schedule.user.nickname %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">使用する車</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-car-wrap'>
      <%= f.collection_select(:car_id, Car.all, :id, :car_name, {prompt: "選択してください"}, {class:'car-select'} ) %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">開始時間</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-schedule-wrap'>
      <%= raw sprintf(
            f.datetime_select(:start_time, 
                {
                :use_month_numbers => true, 
                :minute_step => 10,
                date_separator: '%s',# 年, 月
                datetime_separator: '%s',# 日
                time_separator: '%s'
                }),
                '<p> 年 </p>', '<p> 月 </p>', '<p> 日 </p>', '<p> 時 </p>') + '<p> 分 </p>' %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">終了時間</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-schedule-wrap'>
      <%= raw sprintf(
            f.datetime_select(:end_time, 
                {
                :use_month_numbers => true, 
                :minute_step => 10,
                date_separator: '%s',# 年, 月
                datetime_separator: '%s',# 日
                time_separator: '%s'
                }),
                '<p> 年 </p>', '<p> 月 </p>', '<p> 日 </p>', '<p> 時 </p>') + '<p> 分 </p>' %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">予定</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :title, class:"input-default", id:"schedule-title"%>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">内容</label>
    </div>
    <%= f.text_area :content, class:"input-default", id:"schedule-title"%>
  </div>


  <div class="schedule-edit-submit">
    <%= f.submit "変更する", class:"save-btn"%>
    <%= link_to "戻る", schedule_path(@schedule.id), class:"back-btn"%>
  </div>

<% end %>

app/views/schedules/index.html.erb
<p id="notice" class="notice"><%= notice %></p>

<%= render "shared/header" %>

<div class='event-car-add'>
<% if user_signed_in? %>
  <%= link_to '新規車予約', new_schedule_path ,class: 'event-add' %>
  <%= link_to '車種追加', new_car_path ,class: 'car-add' %>
<% end %>
</div>

<div class='schedule-lists'>
<%= month_calendar events: @schedules do |date, schedules| %>
  
  <div class='schedule-month'><%= date.day %></div>

  <div>
  <% schedules.each do |schedule| %>
    <div>
      <%= link_to Car.find(schedule.car_id).car_name, car_path(schedule.car_id) ,class:"index-car-name"%>
      <%= link_to schedule.user.nickname, schedule_path(schedule.id) ,class:"index-user-name"%>
      <br>
      <%= schedule.start_time.strftime("%H:%M") %> <a>〜</a>
      <%= schedule.end_time.strftime("%H:%M") %>
    </div>
  <% end %>
  </div>

<% end %>
</div>

app/views/schedules/new.html.erb
<div class='form-header'>
  <h1 class='form-header-text'>
    車予約
  </h1>
</div>

<%= form_with(model: @schedule, local: true) do |f| %>

<%= render 'shared/error_messages', model: f.object %>


  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">使用する車</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-car-wrap'>
      <%= f.collection_select(:car_id, Car.all, :id, :car_name, {prompt: "選択してください"}, {class:'car-select'} ) %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">開始時間</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-schedule-wrap'>
      <%= raw sprintf(
            f.datetime_select(:start_time, 
                {
                :use_month_numbers => true, 
                :minute_step => 10,
                date_separator: '%s',# 年, 月
                datetime_separator: '%s',# 日
                time_separator: '%s'
                }),
                '<p> 年 </p>', '<p> 月 </p>', '<p> 日 </p>', '<p> 時 </p>') + '<p> 分 </p>' %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">終了時間</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-schedule-wrap'>
      <%= raw sprintf(
            f.datetime_select(:end_time, 
                {
                :use_month_numbers => true, 
                :minute_step => 10,
                date_separator: '%s',# 年, 月
                datetime_separator: '%s',# 日
                time_separator: '%s'
                }),
                '<p> 年 </p>', '<p> 月 </p>', '<p> 日 </p>', '<p> 時 </p>') + '<p> 分 </p>' %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">予定</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :title, class:"input-default", id:"schedule-title"%>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">内容</label>
    </div>
    <%= f.text_area :content, class:"input-default", id:"schedule-title"%>
  </div>

  <div class="schedule-new-submit">
    <%= f.submit "保存する", class:"save-btn" %>
    <%= link_to "戻る", root_path, class: "back-btn" %>
  </div>

<% end %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<div class='form-header'>
  <h1 class='form-header-text'>
    予定詳細ページ
  </h1>
</div>

<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">タイトル</label>
  </div>
  <p class="schedule-show-text"><%= @schedule.title %></p>
</div>


<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">名前</label>
  </div>
  <p class="schedule-show-text"><%= @schedule.user.nickname %></p>
</div>


<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">日付</label>
  </div>
  <p class="schedule-show-text">
    <%= @schedule.start_time.strftime("%Y-%m-%d") %> 〜
    <%= @schedule.end_time.strftime("%Y-%m-%d") %>
  </p>
</div>


<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">時間</label>
  </div>
  <p class="schedule-show-text">
    <%= @schedule.start_time.strftime("%H:%M") %> <a>〜</a>
    <%= @schedule.end_time.strftime("%H:%M") %>
  </p>
</div>


<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">使う車</label>
  </div>
  <p class="schedule-show-text">
    <%= link_to Car.find(@schedule.car_id).car_name, car_path(@schedule.car_id), class:"schedule-show-link" %>
  </p>
</div>


<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">内容</label>
  </div>
  <p class="schedule-show-text">
    <%= @schedule.content %>
  </p>
</div>

<div class="submit">
<% if user_signed_in? && current_user.id == @schedule.user_id %>
  <%= button_to "編集", edit_schedule_path(@schedule.id), method: :get, class:"edit-btn" %>
  <%= button_to "削除", schedule_path(@schedule.id), method: :delete, data: { confirm: 'Are you Sure?' } ,class:'delete-btn' %>
<% end %>
<%= link_to '戻る', root_path ,class:"back-btn"%>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <h1>CAR SHARING</h1>
  <div class='nav'>
    <ul class='nav-left'>
      <li><%= link_to  '車種一覧', cars_path, class: "brand-list" %></li>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname + 'の予定一覧', user_path(current_user.id), class: "category-list" %></li>
      <% end %>
    </ul>
    <ul class='nav-right'>
      
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
      
    </ul>
  </div>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: ' <<< '), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: ' >>> '), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class='form-header'>
  <h1 class='form-header-text'>
    <p><%= @nickname %>さんの予定一覧</p>
  </h1>
</div>
  

  <%# 現在時刻以降のスクジュールのみ取得 %>
  <% @schedules.each do |schedule| %>
    <% if schedule.start_time.to_time > Date.today.to_time %> 
      <p class="border-line"> ------------------------------------------------------------------------------- </p>
      
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">日付</label>
        </div>
        <p class="user-show-text">
          <%= schedule.start_time.strftime("%Y-%m-%d")  %> 
        </p>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">時間</label>
        </div>
        <p class="user-show-text">
          <%= schedule.start_time.strftime("%H:%M") %> <a>〜</a>
          <%= schedule.end_time.strftime("%H:%M") %>
        </p>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">使用する車</label>
        </div>
        <p class="user-show-text">
          <%= link_to Car.find(schedule.car_id).car_name, car_path(schedule.car_id), class:"schedule-show-link" %>
        </p>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">タイトル</label>
        </div>
        <p class="user-show-text">
          <%= schedule.title %>
        </p>
      </div>

    <% end %>
  <% end %>

  <div class="submit">
    <%= link_to '戻る', root_path, class:'back-btn' %>
  </div>
</div>